services:
  scheduler:
    build:
      context: ./backend
    container_name: symfony_scheduler
    entrypoint: ["/entrypoint-scheduler.sh"]
    command: sh -c "while true; do php bin/console app:update-currencies && sleep 30; done"
    depends_on:
      - db
      - backend
    networks:
      - app

  backend:
    build:
      context: ./backend
    container_name: symfony_backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    ports:
      - "5173:5173"
    networks:
      - app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    networks:
      - app

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge
